### PR TITLE
Convert model for Mimi v1.0.0

### PR DESCRIPTION
**Pull request by lrennels**

### CODE REVIEW

**Comment by davidanthoff** [comment]
Tests here fail, do we know why?

**Comment by lrennels** [comment]
Hmm no I'll look now, they pass when we run dependency tests on Mimi so I'm surprised

**Comment by davidanthoff** [comment]
It might be a precision problem, i.e. our tests might be too demanding in terms of numerical accuracy?

**Comment by lrennels** [comment]
Perhaps, but it does just seem like the inequalities are failing ie.
```
 [2] macro expansion at /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1113 [inlined]
170

Standard API functions: Test Failed at /home/runner/work/MimiRICE2010.jl/MimiRICE2010.jl/test/runtests.jl:148
174 Expression: scc3 < scc2
175 Evaluated: -0.007445819544006788 < -0.01037983214048495
```

... but why that would differ on different systems I'm not sure, I"ll look into this

**Comment by lrennels** [comment]
It's these three comparison operator tests that are failing

```
# Test that it's smaller with a shorter horizon
scc2 = MimiRICE2010.compute_scc(year=2015, last_year=2295)
@test scc2 < scc1

# Test that it's smaller with a smaller prtp
scc3 = MimiRICE2010.compute_scc(year=2015, last_year=2295, prtp=0.02)
@test scc3 < scc2

# Test with a modified model
m = MimiRICE2010.get_model()
update_param!(m, :t2xco2, 5)
scc4 = MimiRICE2010.compute_scc(m, year=2015)
@test scc4 > scc1   # Test that a higher value of climate sensitivty makes the SCC bigger

```

**Comment by davidanthoff** [comment]
Hm, that is not good, actually, because that suggests some real problem, right?

**Comment by lrennels** [comment]
It does, yes. What I don't understand is where the values that are `Evaluated` are coming from.  

```
170 Standard API functions: Test Failed at /home/runner/work/MimiRICE2010.jl/MimiRICE2010.jl/test/runtests.jl:148
174 Expression: scc3 < scc2
175 Evaluated: -0.007445819544006788 < -0.01037983214048495
```

But when I run this on my machine, I get expected values of scc ...

```

julia> scc3
10.236492440779989

julia> scc2
14.27016497172074
```

**Comment by davidanthoff** [comment]
Ok, I suspect that we have some sort of overflow problem with 32 bit integers, which are used on 32 bit platforms if you use a type of `Int`... That would explain why things go wrong on 32 bit platforms only, as far as I can tell.

**Comment by davidanthoff** [comment]
I've just pushed a commit that might fix this.

**Comment by lrennels** [comment]
Oh good find, I was noticing the only type parameterized Ints are years and that couldn't be it. Finger's crossed.

**Pull request merged**
