### PR TITLE
Various small fixes for consistency with Pkg

### PR DESCRIPTION
**Pull request by lrennels**
@davidanthoff  This PR updates the name of the module file to `MimiRICE2010.jl` where necessary to run tests and include a proper `main.jl` file

### CODE REVIEW

**Comment by davidanthoff** [comment]
I think we should handle that differently: we should probably include `marginaldamage.jl` from `MimiRICE2010.jl` (so that it just becomes part of the package and adds some more functions that one can call in the package). And `main.jl` should probably also become included in the package, and then export some function that does the same thing that is currently happening in the global scope.

**Comment by lrennels** [comment]
Sure, I can include `marginal damage.jl` in the module instead. Per `main.jl`, I don't think the package needs it since it doesn't do anything unique, it's more of a template on how people can run the model right?

**Comment by davidanthoff** [comment]
We could move the `main.jl` file into a folder `<root>/examples`? As a template, that is maybe where it should be?

And yes, I think just including the md file in the module is the way to go.

**Comment by lrennels** [comment]
That sounds good, the more I thought about it the more I thought we should perhaps even just delete it and move the information to the README?

**Comment by davidanthoff** [comment]
Yes, the README probably makes most sense!

**Comment by lrennels** [comment]
Good, so for now I've moved the `main.jl` to the root folder, and then added some notes to the README.  Let me know how that looks, I'll use this conversation as a template for how to update the other models.

**Comment by davidanthoff** [comment]
Looks good! I'll do a few more edits here an there, and will open a PR in a bit. And then maybe you can use the combined changes as the template for other packages?

**Comment by lrennels** [comment]
@davidanthoff Yep!  Doing PAGE2009 now!

**Pull request merged**
